name: Bun CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Bun
      run: |
        curl -fsSL https://bun.sh/install | bash
        echo 'export PATH=$HOME/.bun/bin:$PATH' >> $GITHUB_ENV
    - name: Install dependencies
      run: bun install
    - name: Run index.ts
      run: bun run index.ts
